server:
  port: 8085

spring:
  application:
    name: stock-batch
---

spring:
  config:
    activate:
      on-profile: local
    import: optional:configserver:http://localhost:9000
  cloud:
    config:
      username: username
      password: password
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/batch/core/schema-h2.sql
  datasource-meta:
    driver-class-name: org.h2.Driver
    jdbc-url: ${datasource-meta.url}
    username: ${datasource-meta.username}
    password: ${datasource-meta.password}

  datasource-data:
    driver-class-name: org.h2.Driver
    jdbc-url: ${datasource-stock.url}
    username: ${datasource-stock.username}
    password: ${datasource-stock.password}

data-go:
  service-key: ${data-go.service-key}

dart:
  api-key: ${dart.api-key}
---

spring:
  config:
    activate:
      on-profile: dev
    import: optional:configserver:http://localhost:9000
  cloud:
    config:
      username: username
      password: password
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: embedded
      schema: classpath:org/springframework/batch/core/schema-h2.sql
  datasource-meta:
    driver-class-name: org.h2.Driver
    jdbc-url: ${datasource-meta.url}
    username: ${datasource-meta.username}
    password: ${datasource-meta.password}

  datasource-data:
    driver-class-name: org.h2.Driver
    jdbc-url: ${datasource-stock.url}
    username: ${datasource-stock.username}
    password: ${datasource-stock.password}

eureka:
  client:
    register-with-eureka: true
    fetch-registry : true
    service-url:
      defaultZone-url: http://localhost:9000/eureka

data-go:
  service-key: ${data-go.service-key}

dart:
  api-key: ${dart.api-key}